### PR TITLE
Access/focus indicator refactor & pending state

### LINKED ISSUE #63: Focus indicator pending state & refactor
Refactor the AccessIndicator relevant logic in Level into a state machine. This will reduce/eliminate the need for conditional checks in useEffects and simplify everything. You should also add a loading state, which the machine won't get into yet but we'll be able to wire it up later (and the UI will be ready for it)

### PR DESCRIPTION
**Pull request by KovJonas**
Closes #63 

I think I managed to simplify the Level component a lot by making this new state machine (`levelDataMachine`).

I got rid of the `modalfocus` state as we discussed it yesterday, but unfortunately the indicator bar still "jumps" a bit when I close the modal. That's because the `isStakingModalOpen` variable is `false` at the moment when I close the modal, so the guard in the machine allows the state transition from `focus` to `idle`.

For the pending state animation, I made a simple effect with framer motion. I know we don't use that state right now, but you can test it by uncommenting the if block after line ~~54~~ 41 in `AccessIndicator.tsx`. I'm open to new ideas on this one, since I'm not fully satisfied with it.

### CODE REVIEW

**Comment by cs-balazs** [comment]
I don't think it's necessary to `send("FOCUSOUT")` on every `isModalOpen` change, and trigger its guard, instead, we could just send it when we close the modal, since that's the time we really want to do it.
What was the problem with having a different `focus` state for when the modal is open? I can't think of a workaround for the "jumping" without that

**Comment by KovJonas** [comment]
> I don't think it's necessary to `send("FOCUSOUT")` on every `isModalOpen` change, and trigger its guard, instead, we could just send it when we close the modal, since that's the time we really want to do it.

That's a good point, I fixed that in my latest commit, thanks!

> What was the problem with having a different `focus` state for when the modal is open? I can't think of a workaround for the "jumping" without that

We had the same problem ("jumping") with that solution, so using a guard was just a simpler way to manage the state transitions without an extra state. But let me know if you have an idea on how could we solve this jumping issue with the `modalfocus` state, I'd really like to fix that. I thought about using `setTimeout` only when we close the modal, but that felt a little bit "hacky", and I'm not sure if that would work well at the end.

**Comment by KovJonas** [comment]
A quick explanation:
- The state machine has 5 states now: it's in `idle` by default, and it can be in `access` if the user has access to a specific level. I added the `pending` state too, so we can use it in the future. The 2 most interesting states are `focus` and `forcedidle`.
- When the user hovers over a level (with mouse), the indicator will go into `focus` state, but if we catch a `focusin` event, the machine will go to `focus` state only if the "Stake to join" button has the `data-focus-visible-added` attribute.
- When the user closes the staking modal, we're sending a `FOCUSOUT` event to the machine by default, but I also added a click handler on the component, so if the user closes the modal by clicking somewhere (either on the "x" button, or somewhere on the overlay), and the cursor isn't on the Level component, the machine will transition to the `forcedidle` state for just 100ms. After that, it'll transition back to `idle` state. This way it won't go back to `focus` state after closing the modal (even if the "Stake to join button" is technically in focus state), because  it won't do anything on `FOCUSIN` event in `forcedidle` state.

**Comment by cs-balazs** [comment]
What is the difference between the `FOCUSIN` and the `MOUSEFOCUSIN` events? Only the `idle` state reacts to both of them and transitions to the same state. Or is it just for semantics?

---

I think this `useEffect`:
```ts
useEffect(() => {
  if (state.value === "forcedidle") {
    send("IDLE", { delay: 100 })
  }
}, [state])
```
is unnecessary, a delayed transition in the `forcedidle` state like this would do the same I think:
```ts
forcedidle: {
  after: {
    100: "idle",
  },
}
```
If something like this works, we wouldn't need to check the condition every time the state changes.

---

I was also not sure if we need this `useEffect`:
```ts
useEffect(() => {
  state.context.isModalOpen = isModalOpen
}, [isModalOpen])
```
Because if I see it right, the context is only used in the guard, and that guard is only relevant when we make the transition inside `focusLeaveHandler`, so I thought, we could just do this:
```ts
if (!isStakingModalOpen) send("FOCUSOUT")
```
But it doesn't seem to work, which means, that the event is fired before `isStakingModalOpen` would be `true`, which would mean, that the current solution works, because `isStakingModalOpen` is being set to `true` in the time between the event is sent and the guard is processed? Or I'm just missing something here :D

---

> Note: I don't know if you know about this, and just didn't like it, but simple transitions like this: `ACCESS: { target: "access" }` have a shorthand syntax: `ACCESS: "access"`. I'm not saying, it should be like this, it's a personal preference thing I guess, just thought it's worth sharing in case you didn't know :)

**Comment by KovJonas** [comment]
> What is the difference between the FOCUSIN and the MOUSEFOCUSIN events? Only the idle state reacts to both of them and transitions to the same state. Or is it just for semantics?

I used the `MOUSEFOCUSIN` state when we tried different approaches in the last couple of days, but you're right, we only need the `FOCUSIN` state, so I deleted the other one. It might be good in terms of semantics, but at this point I feel like it isn't really necessary, we can understand the code without it.

---

> If something like this works, we wouldn't need to check the condition every time the state changes.

Yep, that works perfectly, and simplifies the code, thanks! 

---

> But it doesn't seem to work, which means, that the event is fired before isStakingModalOpen would be true, which would mean, that the current solution works, because isStakingModalOpen is being set to true in the time between the event is sent and the guard is processed? Or I'm just missing something here :D

Exatly! :D That's why I added that useEffect. So there are two solutions:
1. The useEffect, which you can see in the code right now
2. Or I could add one more event and state (e.g. a `MODALFOCUSOUT` event, which would send the machine to a `modalout`) state, and set a delay on it just like in the `forcedidle` state, which would send the machine to the idle state, and also apply the same guard to this event which we used in the `focus` state on `FOCUSOUT` event.
*Note: I haven't tried this 2nd solution yet, but it should work, since the problem is that the `isStakingModalOpen` changes its state a bit slowly, so a slight delay should solve the problem.*

Both solutions are a bit complicated, but it seems like this is the only way we can make this work. Which one would you prefer?

---

> I'm not saying, it should be like this, it's a personal preference thing I guess, just thought it's worth sharing in case you didn't know :)

Oh, that's a great tip, thanks, I changed to the shorthand syntax, it makes the code a bit cleaner!

---

One more thing: I realized that we don't use the `LOAD` event anywhere, so I also removed that. I used that for something when we worked on the "indicator jumping" issue, just forgot to delete it.

**Comment by cs-balazs** [comment]
I think the current `useEffect` version is better, than having an extra state, `isStakingModalOpen` shouldn't change that often.

I was thinking about a solution like this:
In the `focusLeaveHandler` we send an event like this:
```ts
send("FOCUSOUT", { delay: 100, id: "focusout" })
```
And when we open the modal (in the onClick of the open button) we would cancel the event:
```ts
() => {
  onStakingModalOpen()
  cancel("focusout")
}
```
Was experimenting with this, but the delaying doesn't seem to work, any ideas why? I removed the `useEffect`, the context, and the guard in the machine, and tried only sending the delayed `FOCUSOUT`, but always happens immediately.

I'm not sure if this could work even if the delay would, but it doesn't really matter, I think the current machine implementation is good, maybe later we will have an idea to avoid the context.

**Review by dovalid — APPROVED** [review]

**Pull request merged**
